package com.atlas.inventory.shared.messaging;

public enum ConsumerEventType {
  BOOKING_CREATED,
  BOOKING_CONFIRMED,
  BOOKING_EXPIRED,
  BOOKING_CANCELLED,
  BOOKING_FAILED,

  FLIGHT_CREATED,
  FLIGHT_DELETED,
  FLIGHT_UPDATED,
  HOTEL_CREATED,
  HOTEL_UPDATED,
  HOTEL_DELETED
}
